# Generated by Django 5.0.1 on 2024-07-13 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordEntry',
        ),
    ]
